### ISSUE TITLE
How to set timeout duration?

### ISSUE THREAD

**Issue by seanngpack** [arduino-libraries/ArduinoBLE#100]
I am using bluetooth to controller a stepper motor using the Accelstepper library. The problem is that running the stepper is blocking. So during a long rotation, Arduino BLE drops out. Can I set a timeout duration so this does not happen?

**Comment by Polldo** [comment]
Hi @seanngpack ,
you are probably interested in increasing the link supervision timeout. This parameter is negotiated between central and peripheral when the connection is initialized. 
Try this: https://github.com/Polldo/ArduinoBLE/commit/df8d675cfc13faef810d3791ed20572324b6d54f
You can use `BLE.setSuperivisionTimeout(timeoutValue)`, where timeoutValue can assume values between 10 and 3200. The actual timeout will be (timeoutValue * 10 ms).
