### ISSUE TITLE
setAdvertisedService() conflicts with setManufactureData()

### ISSUE THREAD

**Issue by WB3Tech** [arduino-libraries/ArduinoBLE#103]
Using v.1.1.3, If you set an advertised service, you cannot see any set manufacture data in the advertisement.

**Comment by Polldo** [comment]
Hi @WB3Tech ,
you are right, at the moment an advertised service shadows the manufacturer data. 
I'm already thinking about a possible fix to make scan response and advertising data more flexible. I will let you know.

**Comment by WB3Tech** [comment]
@Polldo,  sounds like you're aware, thanks you!

**Comment by Polldo** [comment]
Fixed here https://github.com/arduino-libraries/ArduinoBLE/pull/117
Examples here https://github.com/arduino-libraries/ArduinoBLE/pull/134
