### ISSUE TITLE
Send keystroke(s) example

### ISSUE THREAD

**Issue by nikolayrantsev** [arduino-libraries/ArduinoBLE#107]
Hi, 
I'm new to the Arduino world, so the question might be quite simple or irrelevant here, 
Appreciate any help,
Could anyone provide an example of how to send keystroke using this library?
I just want to pair ARDUINO NANO 33 BLE with any device and send a few keys, aka Arduino as the custom Bluetooth keyboard controller,
Thanks a lot!

**Comment by Polldo** [comment]
Hi @nikolayrantsev ,
support for HID is not yet available, follow https://github.com/arduino-libraries/ArduinoBLE/issues/7 for news
Thanks
