### ISSUE TITLE
BLE connection from Arduino Hardware not working with latest Windows build19041 

### ISSUE THREAD

**Issue by arpita-agrawal** [arduino-libraries/ArduinoBLE#114]
I uploaded the example sketch LED available with the ArduinoBLE library on Nano 33 BLE Sense. This configures the Nano 33 BLE Sense as a BLE peripheral.

After that, I tried to connect the device to the windows system using Bluetooth LE explorer. It doesn't connect. Before updating windows to the latest  build19041 version the connection was working and I could send and receive the data using Bluetooth LE explorer.

Please note that other BLE devices are successfully connecting to the system via Bluetooth LE explorer even after the windows update.

The serial monitor log shows that the board gets connected and disconnected to the PC again and again.

Please refer to the attached screenshots for more details.

Thanks
Arpita 
![pairing error](https://user-images.githubusercontent.com/37394082/93226198-ae4f3800-f790-11ea-95a7-814411ff7a0c.jpg)
![Serial Monitor log](https://user-images.githubusercontent.com/37394082/93226206-b018fb80-f790-11ea-9531-84c4f70b580f.png)
![Device detected in Bluetooth LE explorer](https://user-images.githubusercontent.com/37394082/93226209-b018fb80-f790-11ea-8466-34e8719dc2b0.jpg)
![exception](https://user-images.githubusercontent.com/37394082/93226211-b0b19200-f790-11ea-9c96-ec4df63b71a6.jpg)
![Failed to connect](https://user-images.githubusercontent.com/37394082/93226214-b14a2880-f790-11ea-9e07-60deadf6cfd1.jpg)

**Comment by Polldo** [comment]
Hi @arpita-agrawal ,
this issue should be fixed here https://github.com/arduino-libraries/ArduinoBLE/pull/95
You could checkout the latest commit of ArduinoBLE and try again

**Comment by arpita-agrawal** [comment]
Hi,

With the fix in #95 the issue is resolved. However, this fix is not available in version 1.1.3 of library.

Thanks
Arpita

**Comment by Polldo** [comment]
Thanks for the feedback, It will be available in the next release!

**Comment by ablankenship10** [comment]
I'm not sure that this is working even with the latest from Master branch. Running the BatteryMonitor example and attempting to connect with BLE Explorer results in the same issue above (Unable to pair, however no Catastrophic error). It is able to connect and starts printing the battery level value to the console for about 20 seconds before the Central (windows pc) disconnects and BLE Explorer shows pairing failed.

Windows version:
![image](https://user-images.githubusercontent.com/1980841/103927221-9ef94f00-50df-11eb-92e6-93a9a5b7a9d6.png)

**Comment by epice500** [comment]
> I'm not sure that this is working even with the latest from Master branch. Running the BatteryMonitor example and attempting to connect with BLE Explorer results in the same issue above (Unable to pair, however no Catastrophic error). It is able to connect and starts printing the battery level value to the console for about 20 seconds before the Central (windows pc) disconnects and BLE Explorer shows pairing failed.
> 
> Windows version:
> ![image](https://user-images.githubusercontent.com/1980841/103927221-9ef94f00-50df-11eb-92e6-93a9a5b7a9d6.png)

I've been having a similar problem. I am working on a BLE device for windows 10 which was working fine last summer, however when I came back to it in December it no longer worked. I traced the issue back to a windows 10 update released sometime around September - October which breaks the functionality of BLE in windows 10... again. I am currently working on a solution as this is a huge setback and Microsoft seems to be blissfully uncaring about the issue.
