### ISSUE TITLE
Add an example for multi connection

### ISSUE THREAD

**Issue by BigKingAlexxx** [arduino-libraries/ArduinoBLE#115]
Hello,

I would really appreciate it, if you could add an example, where multiple centrals are connected to one peripheral and the other way around. I can't get it working myself.

Best regards,
Alex

**Comment by Polldo** [comment]
Hi @BigKingAlexxx ,
this topic is actually a work in progress, check this out https://github.com/arduino-libraries/ArduinoBLE/issues/108 and https://github.com/arduino-libraries/ArduinoBLE/issues/50
Feedbacks would be very useful

**Comment by BigKingAlexxx** [comment]
ok, thank you
