### ISSUE TITLE
MTU negotiation not effective?

### ISSUE THREAD

**Issue by evovolker** [arduino-libraries/ArduinoBLE#14]
Hi 
I am using v1.1.0 of the library with a Nano 33 Iot (NINA w10) and Android API 26. When I request a larger MTU on central I get an apparent success: 
`bleQueue.requestMtu(256);`
`D/BluetoothGatt: onConfigureMTU() - Device=... mtu=242 status=0`

I then write this MTU to the peripheral and use the nearest lower power of 2 (I tried various values, all the same): 
`newMTUsize = 128;`
`dataCharacteristic.setValue(mVals, newMTUsize);` 
However, the byte[] data received on central via 
`final byte[] data = characteristic.getValue();`
has data.length: 34

I found a variable _maxMtu in utils/ATT.cpp set to the conventional 23 - changing this has no observable effect. 

Is this a user, device or code issue? 
__EDIT__
User issue: 
`BLECharacteristic dataCharacteristic(DATA_CHARACTERISTIC_UUID, BLERead | BLEIndicate, origMTUsize);`

**Comment by rishita-asl** [comment]
Hii,

I am facing the same issue here. Did anyone find a solution?
