### ISSUE TITLE
WARNING since updating to ArduinoCore-mbed v2.0.0

### ISSUE THREAD

**Issue by RMLEARNEY** [arduino-libraries/ArduinoBLE#171]
My board is an Arduino Nano BLE 33

```
WARNING: library ArduinoBLE claims to run on samd, megaavr, mbed, apollo3 architecture(s) and may be incompatible with your current board which runs on mbed_nano architecture(s).
```

**Comment by facchinm** [comment]
We need to add `mbed_nano` and `mbed_portenta` architectures. @Polldo can you take care of it?

**Comment by Polldo** [comment]
@facchinm is [this](https://github.com/arduino-libraries/ArduinoBLE/pull/173/commits/d59eb8c454c91b7a62b87dc538ca0250cb076b82) enough?
