### ISSUE TITLE
How to implement on Read callback about BLECharacteristic

### ISSUE THREAD

**Issue by JAICHANGPARK** [arduino-libraries/ArduinoBLE#181]
I'd like to implement on read callback this lib

I tried to set event callback 
but this callback to read write value

**Comment by Polldo** [comment]
Hi @JAICHANGPARK ,
you need to attach an event handler to a characteristic in this way: https://github.com/arduino-libraries/ArduinoBLE/blob/master/examples/Peripheral/CallbackLED/CallbackLED.ino#L57

**Comment by JAICHANGPARK** [comment]
@Polldo  Thank you for comment 
I solved this problem
