### ISSUE TITLE
How TO Speed Up transmission frequency of BLE

### ISSUE THREAD

**Issue by JacksonLtt** [arduino-libraries/ArduinoBLE#217]
### Subject of the issue
How could I speed up transmission frequency of BLE?

### Your workbench
* What platform are you using?
  I am using Arduino to program Arduino Apollo3.
* What version of the device are you using? Is there a firmware version?
  I used [SparkFun Thing Plus - Artemi](https://www.sparkfun.com/products/15574)s as microcontroller. 
 Artemi works as a broadcaster to advertise data. 
 I use Macbook Pro (macOS Big Sur, 2018) as a receiver to receive data from Artemi. I used [PythonNUS ](https://github.com/JacksonLtt/sign_language/blob/main/Arduino/sample%20data/PythonNUS-master/prac.py)to test the transmission rate. 

* How is everything being powered?
   I used USB to power the Artemi.

### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue to a gist.
 
Firstly, I used [code](https://github.com/JacksonLtt/sign_language/tree/main/Arduino/Artemis%20Example/one_byte) to test the transmission rate of BLE. The data size is one byte char.
The transmission rate that I got is around **120-130 Hz** (number of packets/per second)

Secondly, I used my [code ](https://github.com/JacksonLtt/sign_language/blob/main/Arduino/Artemis%20Example/BatteryMonitor_example/byte_220)to test the transmission rate of sending 220 byte via BLE. 
The transmission rate that I got is only **30 Hz** (number of packets/per second)

Please let me know how could I speed up transmission rate of BLE

Thank you [ArduinoBLE](https://github.com/arduino-libraries/ArduinoBLE)
Best regards

**Comment by per1234** [comment]
Hi @JacksonLtt. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
