### ISSUE TITLE
UUIDs must be lower case

### ISSUE THREAD

**Issue by DrRGee** [arduino-libraries/ArduinoBLE#23]
e.g.,

peripheral.characteristic("f000aa22-0451-4000-b000-000000000000");    // WORKS
peripheral.characteristic("F000AA22-0451-4000-B000-000000000000");  // DOES NOT WORK

**Comment by sandeepmistry** [comment]
Hi @DrRGee,

Thanks for opening this, I've proposed some changes in pull request #24 to address this.

We welcome any feedback you have on them. You can download a version of the modified library that includes the changes here: https://github.com/sandeepmistry/ArduinoBLE/archive/uuid-case-insensitive-comparison.zip
