### ISSUE TITLE
Please make a GitHub Release of 1.3.1

### ISSUE THREAD

**Issue by gmacario** [arduino-libraries/ArduinoBLE#240]
I noticed that you released v1.3.1 of the ArduinoBLE library

https://github.com/arduino-libraries/ArduinoBLE/commit/f24f335c54311ef05c99102ba5714fe99340f2db

and a tag "1.3.1" was also added to the git repository

Are you also going to publish a corresponding Release on https://github.com/arduino-libraries/ArduinoBLE/releases ?

Thanks!

**Comment by facchinm** [comment]
Done :wink:
