### ISSUE TITLE
Reading advertising data via arduinoble

### ISSUE THREAD

**Issue by Kaly380** [arduino-libraries/ArduinoBLE#253]
Good morning, I have a Xiomi brand scale that has a ServiceData that sends the data

How can I get the data from the ServideData of the scale

Please help

![image](https://user-images.githubusercontent.com/6775078/186052166-046fbede-fe65-4e18-882a-d1b6e3e7f3e0.png)

**Comment by per1234** [comment]
Hi @Kaly380. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/using-arduino/networking-protocols-and-devices/27

**Comment by Kaly380** [comment]
There is only the functionality implemented but that arduino peripheral mode.

Someone please guide me to work arduino central mode, and I can access the servicedata method and obtain the data of my device
