### ISSUE TITLE
Missing implement BLEAdvertisedDevice

### ISSUE THREAD

**Issue by Kaly380** [arduino-libraries/ArduinoBLE#257]
BLEAdvertisedDevice implementation is not present in ArduinoBLE

**Comment by per1234** [comment]
Hi @Kaly380. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
