### ISSUE TITLE
How to allow \ pair only 1 MAC address to connect? 

### ISSUE THREAD

**Issue by David-Afik** [arduino-libraries/ArduinoBLE#258]
Hello, 
I'm trying to secure my nano and want to allow only 1 MAC address to connect to him 
and also to not publish anything 
so only my known device will be allow to connect to the nano (and if someone will scan - he will not see the nano).

how do I do this ? 
coudn't find any reference anywhere 

Thanks,

**Comment by per1234** [comment]
Hi @David-Afik. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/

**Comment by David-Afik** [comment]
but you wrote the library , can you just say if it's possiable?
and where are the documents for this?

I have ask the forum a week before I got here - no one known 
it's seem like a very somple thing to do - but canI do this?
