### ISSUE TITLE
BLEPeripheral not working on custom board

### ISSUE THREAD

**Issue by celiafb** [arduino-libraries/ArduinoBLE#262]
Hello,

I'm using the Fanstel BC832 module which contains Nordic's nRF52832 BLE chip on a custom PCB board. When trying to run the Blinky example on PlatformIO, it works perfectly. However, when trying to run any of the BLE examples that use the BLEPeripheral library, the code gets flashed to my module but I can tell the module doesn't even reach the setup loop (where I set some GPIO lines high and low but I never observed this on the scope). Instead, the LED2 pin shows little short blips (3 V, about 3 us long, spaced about 110 ms apart). I tried flashing two different modules and the same behavior is occurring. I'm thinking this probably has to do with an issue of the crystal initialization, but I'm not really familiar with the details of this library (I was previously using Segger and recently moved to PlatformIO with the Arduino environment).
Does anyone have any suggestions as to what I can try to make the BLE examples work?

Thank you in advance!!

**Comment by per1234** [comment]
Hi @celiafb. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
