### ISSUE TITLE
ArduinoBLE with Magicbit

### ISSUE THREAD

**Issue by sswartley** [arduino-libraries/ArduinoBLE#279]
Hello,

I am trying to use ArduinoBLE with [Magicbit](https://magicbit.cc/magicbit-core/). I am trying to use it as a Central and Scan for a [Vernier Go Direct Temperature sensor](https://www.vernier.com/product/go-direct-temperature-probe/). When I run the Scan example it does not find the sensor, although it finds a few Bluetooth devices. This is an ESP32 device and so my expectation was for it to work. If I run the same example with a [different ESP32 device](https://www.sparkfun.com/products/19177) I am able to find the sensor, as well as many more Bluetooth devices. Any ideas on why this ESP32 device is not performing?

Thanks,

Sam

**Comment by per1234** [comment]
Hi @sswartley. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
