### ISSUE TITLE
Unexpected behaviour of device argument in connect/disconnect callback functions

### ISSUE THREAD

**Issue by s-a-i-m-o-n** [arduino-libraries/ArduinoBLE#290]
Using the BLE library we can set callback which are called when a device connects or disconnects

```cpp
// assign event handlers
BLE.setEventHandler(BLEConnected, connectHandler);
BLE.setEventHandler(BLEDisconnected, disconnectHandler);
```

The callback functions have the following form:
```cpp
void connectHandler(BLEDevice peripheral) {
  Serial.println(peripheral.localName()); // prints nothing
  Serial.println(peripheral.address()); // prints address
}
```

However, when accessing the ble device variable passed to the function is not working as expected. 
For example accessing `.address()` will return the address of the device as expected.
However, accessing `.localName()` will return an empty string even though when the device has a local name set.
(I can print the localName just fine if I first use `BLE.scanForName()` and then `.localName()` in the `setup` or `loop` function).

Note: This is my first post on GIT-Hub, go easy on me.

**Comment by rmlearney-digicatapult** [comment]
Your interrupt handler probably takes too long to execute. Instead you should just set a flag in the handler which your main loop picks up and then executes the very slow retrieval of peripheral name, address, and then serial writes.

**Comment by s-a-i-m-o-n** [comment]
Sorry for my late reply. I did not find time up to know to try out your suggestion.

I trimmed the code inside the handlers and do the main work inside the main loop. I use a queue instead of flags to react to connect/disconnect/receive events inside the main loop. Everything seems to work fine now. Thank you.
