### ISSUE TITLE
Arduino Ble MTU

### ISSUE THREAD

**Issue by pranjul-arctano** [arduino-libraries/ArduinoBLE#297]
I am just trying to send data by BLE, to and from by using two Arduino Nano33 Iot devices, One is Peripheral(Server) and other is Central(client). Earlier when connecting with just a mobile application I was able to send data of more than 20 bytes easily without any problem, But the problem arises when I tried to between two Arduino Nano33 IOT devices. The problem is mainly arising is that I am not able to send and receive data more than 20 bytes. I tried changing max MTU value in ATT.h library file but that does not work as well. After trying with different approach I was able to change MAX_AD_DATA_LENGTH which was 31 earlier in BLEAdvertisingdata.h by doing so I am able to send data of more than 20 bytes but not able to receive data from central device.Tried most of the possible things, can anyone tell me what to do at the central device side so that I would be able to receive data at the peripheral as well.
Thank you

**Comment by paulvha** [comment]
First the process :

During BLE.begin() (in local/BLELocalDevice.cpp) it will call HCI.readLeBufferSize().  In this function part of utility/HCI.cpp, it will determine the maximum packet size your board can handle based on the HCI-chip layer. It will update the default size with a call to ATT.setMaxMtu(). 

Once the central is connected, from the sketch you will perform a BLE.discoverAttributes() (in utility/ATT.cpp). From here it will call exchangeMtu(). In this function, the central will send its MaxMtu and the peripheral will compare against his discovered MaxMtu. Then it will return the lowest value (either the central or peripheral MaxMTU). That returned value is handled in central in mtuResp() (in utility/ATT.cpp)

You can add Serial.println() on different places to understand where the breakdown is happening. The Nano 33 IOT is using the WA102 from ublox, but I can not find information on the maximum MTU-size that it supports

regards,
Paul
