### ISSUE TITLE
Issue in the disconnection event

### ISSUE THREAD

**Issue by cparata** [arduino-libraries/ArduinoBLE#30]
Hi @sandeepmistry ,
I found a bug in the management of the disconnection event. Basically, the prototype of the "removeConnection" API has bad parameters that do not match the type of the relative variables. In particular, with the current code, the handle is truncated from uint16_t to uint8_t and it causes bad handle values, so I'm not able to get the disconnection notifications on my side.
You can find the fix for this issue in the STM32duinoBLE fork:

https://github.com/stm32duino/STM32duinoBLE/pull/4

Best Regards,
Carlo

**Comment by sandeepmistry** [comment]
Hi @cparata,

Many thanks for letting us know, I've cherry picked your commit into this repo: https://github.com/arduino-libraries/ArduinoBLE/commit/d6fba6a66babd7fd4b4f8d63c553d7e19a4caf1b
