### ISSUE TITLE
BLE Long Range or Incresing Tx Power

### ISSUE THREAD

**Issue by gsmith0123** [arduino-libraries/ArduinoBLE#314]
I want to either increase the Tx power or change the settings to activate BLE long range. At the moment my project only gets a max range of about 16-20 Ft. I want to double this range by activating BLE long range or increasing the Tx output. Can you please let me know how to do either of these things? I tried to located the file where you manipulate the bits/registers of the Arduino BLE 33 microcontroller to activate BLE, that way i could try to just follow the data sheet and change to this type of BLE myself, but i ended up failing at this. My Bachelor Degree depends on this project working. Please help.

**Comment by gsmith0123** [comment]
By the way, I am using two Arduino BLE 33's. I know this means that both of these microcontrollers have the ability to increase their range, but Arduino makes it difficult to manipulate the microcontroller on a bit and register level.

**Comment by per1234** [comment]
Hi @gsmith0123. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
