### ISSUE TITLE
BLE.begin() succeeds only the first time in Arduino giga

### ISSUE THREAD

**Issue by FalsinSoft** [arduino-libraries/ArduinoBLE#362]
Running this code in Arduino giga:

```
void loop()
{
  if(BLE.begin())
    Serial.println("OK");
  else
    Serial.println("KO");

  BLE.end();
}
```

show OK only the first time. For all subsequent calls it always show KO and this make impossible to use bluetooth again after the first end().

**Comment by per1234** [comment]
Hi @FalsinSoft. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino-libraries/ArduinoBLE/issues/158.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
