### ISSUE TITLE
Advertiment raw data

### ISSUE THREAD

**Issue by ixj111** [arduino-libraries/ArduinoBLE#39]
Hi, 

I am wondering if there is a method for reading BLE raw data?

Thanks

**Comment by sandeepmistry** [comment]
Hi @ixj111,

This is not supported, and there are no plans to support it. What you requested in #38 is a better approach.

**Comment by Nailer** [comment]
I need this function as well, as I will be using the advertisement data to transfer sensor data without the need to connect to the BLE-device. For now, I will make my own alterations to read from the _eirData buffer, but it could be nice to have a support for this in the library itself.
