### ISSUE TITLE
Dangling pointer in setManufacturerData with explicit company ID

### ISSUE THREAD

**Issue by Biohazard90** [arduino-libraries/ArduinoBLE#56]
This code sets the member _manufacturerData to an array on the stack:
 
https://github.com/arduino-libraries/ArduinoBLE/blob/master/src/utility/GAP.cpp#L63

the program may crash or write nonsense into the advertising data when dereferencing that pointer again in:

https://github.com/arduino-libraries/ArduinoBLE/blob/master/src/utility/GAP.cpp#L108

**Comment by facchinm** [comment]
Hi @Biohazard90 ,
you are very right indeed! Thanks for reporting. Would you mind submitting a PR to fix it so we can give the proper attribution?
