### ISSUE TITLE
central.address() function returns wrong value

### ISSUE THREAD

**Issue by fgaetani** [arduino-libraries/ArduinoBLE#62]
Hi, I noticed this issure on Arduino Nano 33 BLE board, the central.address() function returns an incorrect MAC address. In addition, the value also not appears to be unique and change despite being reconnected to the same central device. I await news for the solution.

**Comment by facchinm** [comment]
Hi @fgaetani ,
are you using a phone as central? This could be an address randomizer feature of recent mobile operating systems. Do you have the chance to try calling `central.address()` while connecting to another nano?

**Comment by fgaetani** [comment]
Hi @facchinm ,
yes, I use a smartphone, I have tried both Android and iOS obtaining the same result, I did not know this randomization technique. Is it therefore not possible to obtain the real physical address?

**Comment by Nailer** [comment]
> Hi @facchinm ,
> yes, I use a smartphone, I have tried both Android and iOS obtaining the same result, I did not know this randomization technique. Is it therefore not possible to obtain the real physical address?

He is correct. Due to privacy reasons, devices no longer send a fixed address that you can store. This can be toggled on newer Android phones, but is always turned on in iOS.
