### ISSUE TITLE
Set Transimission Power via Manufacturer Data

### ISSUE THREAD

**Issue by John-Almardeny** [arduino-libraries/ArduinoBLE#75]
Hi,
I have been searching for this for long long time now, but failed drastically to find any tips. Your help is very much appreciated.

I am using `ArduinoBLE` Library on Arduino Nano 33 IoT.
There is no method to `setTxPower()` in it. I need to lower the transmission power to limit the BLE advertising range within 2 to 3 meters.

Some people suggested using `setManufacturerData()` method in the same library. However, I have no clue what data to write in it, or even if the transmission power can be changed like that way in the first place.

Looking forward to hearing from you,
Many Thanks.

**Comment by Polldo** [comment]
Hi @John-Almardeny ,
as you noticed, a function for setting the radio tx power has not yet been implemented. Follow this enhancement request to be updated.https://github.com/arduino-libraries/ArduinoBLE/issues/52 
Also, writing the tx power in the manufacturer's data will not affect the actual tx power. In fact it is just a way to inform other devices about the tx power value used.
