### ISSUE TITLE
connect / discover / notify problems

### ISSUE THREAD

**Issue by AndreasLamparter** [arduino-libraries/ArduinoBLE#76]
Hello,

i tried to make my one cycle power meter and used the arduino nano ble as playground.

I created the ble code with Cycling Power Measurement service and my own configuration service. I test the service and characteristics with nRF Connect App on android.

One of my problems is the disconnect bug of a central described in #45.

The second and main problem is: 
The nRF app finds my device and can connect to it. But it can sometimes discover the services and show the characteristics, sometimes not. 
1. Sometimes no characteristics are shown (disconnected ?)
2. Sometimes it can show the characteristics but there are shown grayed
3. Sometimes it can show the characteristics and i can read a value but after a short time i get no results anymore

DevEnv: VSCode + platformio
nRF Connect: https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=de
Solution: [test.zip](https://github.com/arduino-libraries/ArduinoBLE/files/4632875/test.zip)

Best regards
Andreas

**Comment by ElreboCM** [comment]
IMHO you should include your code directly in your issue and not in a separate zip.
