### ISSUE TITLE
Broadcast data as Service UUID Characteristic is false ?

### ISSUE THREAD

**Issue by nico7885** [arduino-libraries/ArduinoBLE#80]
/*
 * Trame result:
0x02 0x01 0x06 -> ok
0x03 0x02 0xCCBB -> ok
0x05 0x16 0x11800203 -> Why 0118 ?(0x1801) the UUID is "0405"
*/ 

BLEService service("BBCC");
BLECharacteristic sdata("0405", BLEBroadcast, 2);

byte tab[] = {0x02, 0x03};

BLE.setAdvertisedService(service);
service.addCharacteristic(sdata);
  
sdata.broadcast();
sdata.writeValue(eddystone, 2);

BLE.addService(service);
BLE.advertise();

**Comment by Polldo** [comment]
Hi @nico7885 ,
The problem with your sketch is that the service is added after its characteristic. It should be the opposite :
```C++
BLE.addService(service);
BLE.setAdvertisedService(service);
service.addCharacteristic(sdata);

sdata.broadcast();
sdata.writeValue(eddystone, 2);
```
In this way, the advertising packet will include a Service Data with the following format: `0xCCBB0203`, where `BBCC` is the service uuid and 0203 is the value of the service data to be broadcast.
