### ISSUE TITLE
my Eddystone UID test example has no service data [Error in ArduinoBLE library]

### ISSUE THREAD

**Issue by Gerriko** [arduino-libraries/ArduinoBLE#82]
I created an Eddystone UID example, but it is not working correctly. Please see my post on Arduino Forum: https://forum.arduino.cc/index.php?topic=687074.0

From what I can see is that when I use "setLocalName" this data is added to the service data (as seen via the phone's BLE utility apps).

I had a look at the library. In the GAPClass::GAPClass()  there is  _localName(NULL) and this variable is set via this function "setLocalName". This in turn is added to the scanResponseData.

Now, looking at the GAPClass::GAPClass() there is in fact  _serviceData(NULL) and _serviceDataLength(0). These two variables are never set, or I could not find where they are set. Thus as far as I can see, this logic fails within the function int GAPClass::advertise():
```c++
if (_serviceData && _serviceDataLength > 0 && advertisingDataLen >= (_serviceDataLength + 4)) {
  advertisingData[advertisingDataLen++] = _serviceDataLength + 3;
  advertisingData[advertisingDataLen++] = 0x16;

  memcpy(&advertisingData[advertisingDataLen], &_serviceDataUuid, sizeof(_serviceDataUuid));
  advertisingDataLen += sizeof(_serviceDataUuid);

  memcpy(&advertisingData[advertisingDataLen], _serviceData, _serviceDataLength);
  advertisingDataLen += _serviceDataLength;
}
```
Is this intentional?

My understanding is that the Eddystone format is serviceData and not scanResponseData. As such it cannot work as it stands.

**Comment by Gerriko** [comment]
I am looking at this line of code again (int GAPClass::advertise()) in GAP.cpp:

_if (_serviceData != NULL && _serviceDataLength > 0 && advertisingDataLen >= (_serviceDataLength + 4)) { ...}

I think this should read...

_if (_serviceData != NULL && _serviceDataLength > 0 && **31 >= (_serviceDataLength + 4)**) { ...}

As in you, do never want to have (serviceDataLength+4) to be greater than the allowable max advertising length which is 31 bytes....

If you had used a const for max Advertising length then this would have been easier to spot... I see you hard code the value "31" in quite a few places.

**Comment by Gerriko** [comment]
I too made an error. After rechecking again I believe that line of code should read:

_if (_serviceData != NULL && _serviceDataLength > 0 &&  (advertisingDataLen 
 + _serviceDataLength + 4) <= 31) { ... }

**Comment by rmlearney-digicatapult** [comment]
If this fixes your issue, would you submit a PR for others who might come across this problem in the future?

**Comment by Polldo** [comment]
Fixed. See https://github.com/arduino-libraries/ArduinoBLE/commit/633e1aa049549fa5b8f60bd9e0baae6f8f5c4d37
