### ISSUE TITLE
Service data isn't added to the advertisting packet

### ISSUE THREAD

**Issue by ippie52** [arduino-libraries/ArduinoBLE#85]
https://github.com/arduino-libraries/ArduinoBLE/blob/3b228dc90262751bdac97712a6c7bda95fcf3a5c/src/utility/GAP.cpp#L113

In this if-statement, it appears that the second condition of the and, `advertisingDataLen >= (_serviceDataLength + 4)` is checking for whether the length of adding the service data is less than the amount of bytes currently used in the advertising data, rather than there being enough free room in the buffer.

I believe this should instead be something more like:
`(sizeof(advertisingData) - advertisingDataLen) >= (_serviceDataLength + 4)`.

When testing with this change, my attempts to add Eddystone service data began working, whilst previously any data beyond an incomplete 16-bit UUID list was not being added.

In addition to this, further down on line 156: https://github.com/arduino-libraries/ArduinoBLE/blob/3b228dc90262751bdac97712a6c7bda95fcf3a5c/src/utility/GAP.cpp#L156, `_advertising` is set to `false`. Nowhere in the file is `_advertising` set to `true`. I believe it's either irrelevant or should be set to true so that `bool GAPClass::advertising()` works.

**Comment by Polldo** [comment]
Fixed https://github.com/arduino-libraries/ArduinoBLE/commit/633e1aa049549fa5b8f60bd9e0baae6f8f5c4d37 https://github.com/arduino-libraries/ArduinoBLE/commit/405c59feb2b174cb6ddb19d59c70fb88b826b1ad
