### ISSUE TITLE
Underlying Nordic Library/API

### ISSUE THREAD

**Issue by sastorer-ms** [arduino-libraries/ArduinoBLE#87]
Do you know which underlying Nordic Library/API this communicates with?

Does this library communicate with an underlying Nordic Library/API at all? If not what  was the reasoning for that decision? At least for the Nano 33 BLE (which is based on the nRF52840 microcontroller) integration with an existing solution for many of the things this library tries to achieve would be possible. 

See: https://www.nordicsemi.com/Software-and-tools/Software/S140

@sandeepmistry

**Comment by facchinm** [comment]
Hi @sastorer-ms , we don't interact with Nordic Softdevice because we decided to go full opensource with Cordio stack on Nano33BLE. [This](https://github.com/arduino-libraries/ArduinoBLE/blob/master/src/utility/HCICordioTransport.cpp) is the porting layer.
