### ISSUE TITLE
[MKR 1010] - Pair with smartphone

### ISSUE THREAD

**Issue by Davidffry** [arduino-libraries/ArduinoBLE#97]
Hi, 

I would like to pair my smartphone and my arduino mkr 1010, it seems that it couldn't to be pairing, can you confirm it?

**Comment by Naphier** [comment]
BLE (Bluetooth Low Energy) doesn't require "pairing". It's done via device discovery -> service discovery -> characteristic discovery & read/listen or write. The "LightBlue" app on the play store is really helpful in testing. 

Pairing doesn't work with the BLE library. If you want pairing then you'll probably want to use Bluetooth classic via the Serial port class. Most BLE chips for arduino don't ship with Bluetooth Classic enabled. There may be a way to change that via firmware, but I doubt that's what you want.

If you've already attempted to pair the device with your phone, remove it from the paired device lists. Explore its BLE services and characteristics via LightBlue app.

**Comment by Davidffry** [comment]
Thanks for your answer, you're right, no pairing works with this library.

to use the ArduinoBLE with smartphone, I create an android app with MIT App Inventor, and it works : 
![image](https://user-images.githubusercontent.com/31964077/87763581-4ecabf80-c815-11ea-858f-00e21cad94a1.png)

now I search how to write to mkr or read from mkr, any ideas?
